apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_NAME
          valueFrom:
            secretKeyRef:
              name: byecom-secret
              key: POSTGRES_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: byecom-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: byecom-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: byecom-secret
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: byecom-secret
              key: POSTGRES_PORT
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: byecom-secret
              key: POSTGRES_URL
        ports:
        - containerPort: 5432