// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/category": {
            "get": {
                "description": "Showing category details in admin side",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Category"
                ],
                "summary": "Category Show",
                "responses": {}
            },
            "put": {
                "description": "Editing category with it's details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Category"
                ],
                "summary": "Category Edit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Add Category",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Add Category",
                        "name": "cat",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AddCat"
                        }
                    }
                ],
                "responses": {}
            },
            "post": {
                "description": "Adding category with it's details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Category"
                ],
                "summary": "Category Add",
                "parameters": [
                    {
                        "description": "Add Category",
                        "name": "cat",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AddCat"
                        }
                    }
                ],
                "responses": {}
            },
            "delete": {
                "description": "Deleting category completely",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Category"
                ],
                "summary": "Category Delete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name search by id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {}
            },
            "patch": {
                "description": "Blocking or unblocking category with products",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Category"
                ],
                "summary": "Category Blocking/Unblocking",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name search by id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/admin/coupon": {
            "get": {
                "description": "Showing Coupon details in admin side",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Coupon"
                ],
                "summary": "Coupon Show",
                "responses": {}
            },
            "put": {
                "description": "Editing Coupon with it's details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Coupon"
                ],
                "summary": "Coupon Edit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name search by id",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "description": "Edit Coupon",
                        "name": "rc",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Coup"
                        }
                    }
                ],
                "responses": {}
            },
            "post": {
                "description": "Adding Coupon with it's details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Coupon"
                ],
                "summary": "Coupon Add",
                "parameters": [
                    {
                        "description": "Add Coupon",
                        "name": "rcc",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Coup"
                        }
                    }
                ],
                "responses": {}
            },
            "delete": {
                "description": "Deleting coupon completely",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Coupon"
                ],
                "summary": "Coupon Delete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name search by id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/admin/login": {
            "post": {
                "description": "Admin Login with email and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Admin Login",
                "parameters": [
                    {
                        "description": "Admin Login",
                        "name": "adminlog",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Login"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/admin/logout": {
            "delete": {
                "description": "Admin Logout by clearing cookie",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Admin Logout",
                "responses": {}
            }
        },
        "/admin/order": {
            "get": {
                "description": "Showing orders details in admin side",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Order"
                ],
                "summary": "Orders Show",
                "responses": {}
            },
            "patch": {
                "description": "Changing order status on any order by admin",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Order"
                ],
                "summary": "Order status change",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Status of order",
                        "name": "status",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name search by order",
                        "name": "order",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/admin/product": {
            "get": {
                "description": "Showing Products details in admin side",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Product"
                ],
                "summary": "Products Show",
                "responses": {}
            },
            "put": {
                "description": "Editing Product with it's details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Product"
                ],
                "summary": "Product Edit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name search by id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Product Name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Product Price",
                        "name": "price",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Product Color",
                        "name": "color",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Product Quantity",
                        "name": "quantity",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Product Description",
                        "name": "description",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Product Category",
                        "name": "category",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "file"
                        },
                        "collectionFormat": "csv",
                        "description": "Product Image",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "post": {
                "description": "Adding Product with it's details",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Product"
                ],
                "summary": "Product Add",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product Name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Product Price",
                        "name": "price",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Product Color",
                        "name": "color",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Product Quantity",
                        "name": "quantity",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Product Description",
                        "name": "description",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Product Category",
                        "name": "category",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "file"
                        },
                        "collectionFormat": "csv",
                        "description": "Product Image",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "delete": {
                "description": "Deleting product completely",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Product"
                ],
                "summary": "Product Delete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name search by id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/admin/report": {
            "get": {
                "description": "Showing sales details in admin side",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Report"
                ],
                "summary": "Report Show",
                "responses": {}
            }
        },
        "/admin/user": {
            "get": {
                "description": "Showing Users details in admin side",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin User"
                ],
                "summary": "Users Show",
                "responses": {}
            },
            "patch": {
                "description": "Blocking or unblocking User",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin User"
                ],
                "summary": "User Blocking/Unblocking",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name search by id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/user/address": {
            "post": {
                "description": "Adding Address with it's details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Address"
                ],
                "summary": "Address Add",
                "parameters": [
                    {
                        "description": "Add Address",
                        "name": "address",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Address"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "models.AddCat": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.Address": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "landmark": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "integer"
                },
                "pincode": {
                    "type": "integer"
                },
                "state": {
                    "type": "string"
                },
                "user_Id": {
                    "type": "integer"
                }
            }
        },
        "models.Coup": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "condition": {
                    "type": "integer"
                },
                "day": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "off": {
                    "type": "integer"
                }
            }
        },
        "models.Login": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "pass": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "B Y E C O M  LTD",
	Description:      "B Y E C O M  is your ecom. shop solution, where you can sell anything online with ease and at an affordable price. We provide an eCommerce platform for businesses to sell their products online and connect with customers worldwide.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
